# Data Preparation

We are not using all the variables in the original dataset. For this project we will only employ the main statistics:
1) For the players:
    - Player value (in Euros)
    - Overall rating
    - Player's main position
    - Pace
    - Shooting
    - Passing
    - Dribbling
    - Defending
    - Physical
    - Nationality

2) For the goalkeepers:
    - Player value (in Euros)
    - Overall rating
    - Player's position
    - Diving
    - Handling
    - Kicking
    - Reflexes
    - Speed (of diving)
    - Positioning
    - Nationality

In [ ]:
#Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys

## Data Loading

In [17]:
df = pd.read_csv("~/pricing-fifa/data/players_20.csv")
df.describe()

,sofifa_id,age,height_cm,weight_kg,overall,potential,value_eur,wage_eur,international_reputation,weak_foot,...,mentality_penalties,mentality_composure,defending_marking,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes
count,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,1.827800e+04,18278.000000,18278.000000,18278.000000,...,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000,18278.000000
mean,219738.864482,25.283291,181.362184,75.276343,66.244994,71.546887,2.484038e+06,9456.942773,1.103184,2.944250,...,48.383357,58.528778,46.848889,47.640333,45.606631,16.572765,16.354853,16.212934,16.368038,16.709924
std,27960.200461,4.656964,6.756961,7.047744,6.949953,6.139669,5.585481e+06,21351.714095,0.378861,0.664656,...,15.708099,11.880840,20.091287,21.585641,21.217734,17.738069,16.996925,16.613665,17.136497,18.038125
min,768.000000,16.000000,156.000000,50.000000,48.000000,49.000000,0.000000e+00,0.000000,1.000000,1.000000,...,7.000000,12.000000,1.000000,5.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,204445.500000,22.000000,177.000000,70.000000,62.000000,67.000000,3.250000e+05,1000.000000,1.000000,3.000000,...,39.000000,51.000000,29.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,226165.000000,25.000000,181.000000,75.000000,66.000000,71.000000,7.000000e+05,3000.000000,1.000000,3.000000,...,49.000000,60.000000,52.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,240795.750000,29.000000,186.000000,80.000000,71.000000,75.000000,2.100000e+06,8000.000000,1.000000,3.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,252905.000000,42.000000,205.000000,110.000000,94.000000,95.000000,1.055000e+08,565000.000000,5.000000,5.000000,...,92.000000,96.000000,94.000000,92.000000,90.000000,90.000000,92.000000,93.000000,91.000000,92.000000

## Data wrangling

In [28]:
#Data wrangling to chose only the relevant columns
df_players=df[['short_name','value_eur', 'overall','player_positions', 'pace',
                'shooting', 'passing', 'dribbling', 'defending',
                  'physic', 'nationality']].reset_index(drop=True)
df_players=df_players[df_players['player_positions'].str.contains('GK')==False]
df_players['value_eur'] = df_players['value_eur'].astype('int')
df_players['player_positions'] = df_players['player_positions'].str.split(',').str[0]
df_players.head(10)

,short_name,value_eur,overall,player_positions,pace,shooting,passing,dribbling,defending,physic,nationality
0,L. Messi,95500000,94,RW,87.0,92.0,92.0,96.0,39.0,66.0,Argentina
1,Cristiano Ronaldo,58500000,93,ST,90.0,93.0,82.0,89.0,35.0,78.0,Portugal
2,Neymar Jr,105500000,92,LW,91.0,85.0,87.0,95.0,32.0,58.0,Brazil
4,E. Hazard,90000000,91,LW,91.0,83.0,86.0,94.0,35.0,66.0,Belgium
5,K. De Bruyne,90000000,91,CAM,76.0,86.0,92.0,86.0,61.0,78.0,Belgium
7,V. van Dijk,78000000,90,CB,77.0,60.0,70.0,71.0,90.0,86.0,Netherlands
8,L. Modrić,45000000,90,CM,74.0,76.0,89.0,89.0,72.0,66.0,Croatia
9,M. Salah,80500000,90,RW,93.0,86.0,81.0,89.0,45.0,74.0,Egypt
10,K. Mbappé,93500000,89,ST,96.0,84.0,78.0,90.0,39.0,75.0,France
11,K. Koulibaly,67500000,89,CB,71.0,28.0,54.0,67.0,89.0,87.0,Senegal

In [30]:
#Create the df for goalkeepers
df_gk=df[df['player_positions'].str.contains('GK')==True]
df_gk=df_gk[['short_name','value_eur', 'overall','player_positions','gk_diving', 
             'gk_handling', 'gk_kicking', 'gk_reflexes', 'gk_speed', 
             'gk_positioning', 'nationality']].reset_index(drop=True)
df_gk['value_eur'] = df_gk['value_eur'].astype('int')
df_gk.head(10)

,short_name,value_eur,overall,player_positions,gk_diving,gk_handling,gk_kicking,gk_reflexes,gk_speed,gk_positioning,nationality
0,J. Oblak,77500000,91,GK,87.0,92.0,78.0,89.0,52.0,90.0,Slovenia
1,M. ter Stegen,67500000,90,GK,88.0,85.0,88.0,90.0,45.0,88.0,Germany
2,Alisson,58000000,89,GK,85.0,84.0,85.0,89.0,51.0,90.0,Brazil
3,De Gea,56000000,89,GK,90.0,84.0,81.0,92.0,58.0,85.0,Spain
4,Ederson,54500000,88,GK,86.0,82.0,93.0,88.0,63.0,86.0,Brazil
5,T. Courtois,48000000,88,GK,85.0,89.0,72.0,87.0,49.0,85.0,Belgium
6,S. Handanovič,26000000,88,GK,88.0,85.0,69.0,89.0,53.0,89.0,Slovenia
7,M. Neuer,32000000,88,GK,87.0,87.0,91.0,87.0,57.0,85.0,Germany
8,H. Lloris,36000000,88,GK,89.0,82.0,68.0,91.0,63.0,84.0,France
9,K. Navas,30500000,87,GK,90.0,81.0,75.0,90.0,53.0,82.0,Costa Rica

In [31]:
#Saving the dataframes
df_players.to_csv('~/pricing-fifa/data/players.csv', index=False)
df_gk.to_csv('~/pricing-fifa/data/goalkeepers.csv', index=False)